app-name: WiFi Share
server:
  port: 8762
amazon:
  access:
    key: cuyev
    secret-key: xsmjy
  region: us-east-1
  endpoint:
    url: http://localhost:8000/
security:
  jwt:
    secret: 9FjialXID-Nhay-OZASgUURSVDbJkDaxGbeGXx6_bzYuv_t4biEhEXld2YkFwbeu